#pragma once
//命令的枚举
enum CMD
{
	CMD_LOGIN = 1,//登录
	CMD_LOGIN_RESULT = 201,//登录结果
	CMD_LOGOUT = 2,//登出
	CMD_LOGOUT_RESULT = 202,
	CMD_NEWUSER_JOIN = 3,
	CMD_NEWUSER_JOIN_RESULT = 203,
	CMD_ERROR = 0,//命令错误
	CMD_ERROR_RESULT = 400
};